language: python
python:
  - "2.7"
# command to install dependencies
install: sh install.sh
# command to run tests
script: 
  - . venv/bin/activate
  - cd test
  - ./test_BC.sh
  - ./test_L.sh
  - ./test_CM.sh
  - ./test_DCC.sh
