language: python
python:
  - "3.6"
# command to install dependencies
install: sh install.sh
# command to run tests
script:
  - . venv/bin/activate
  - cd test
#  - ./test_BC.sh
#  - ./test_L.sh
#  - ./test_CM.sh
#  - ./test_DCC.sh
#  - ./test_PRS.sh
  - ./test_CP.sh
