name: mdmtaskweb
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6.13
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - argon2-cffi=20.1.0=py36h8f6f2f9_2
  - astunparse=1.6.3=pyhd8ed1ab_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - biopython=1.79=py36h8f6f2f9_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - blosc=1.21.0=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.5.30=ha878542_0
  - cffi=1.14.6=py36hc120d54_0
  - cycler=0.10.0=py_2
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=h0708190_1
  - hdf5=1.12.1=nompi_h2750804_100
  - icu=67.1=he1b5a44_0
  - importlib-metadata=4.8.1=py36h5fab9bb_0
  - ipykernel=5.5.5=py36hcb3619a_0
  - ipython=5.8.0=py36_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.4=pyhd8ed1ab_0
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=7.0.2=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py36h5fab9bb_0
  - jupyterlab_widgets=1.0.1=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py36h2531618_0
  - krb5=1.19.2=hcc1bbae_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=11_linux64_openblas
  - libcblas=3.9.0=11_linux64_openblas
  - libcurl=7.78.0=h2574ce0_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc-ng=11.1.0=hc902ee8_8
  - libgfortran-ng=11.1.0=h69a702a_8
  - libgfortran5=11.1.0=h6c583b3_8
  - libgomp=11.1.0=hc902ee8_8
  - liblapack=3.9.0=11_linux64_openblas
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha56f1ee_0
  - libstdcxx-ng=11.1.0=h56837e0_8
  - lzo=2.10=h516909a_1000
  - markupsafe=2.0.1=py36h8f6f2f9_0
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py36h5fdd944_1
  - mdtraj=1.9.6=py36ha895b3a_1
  - mistune=0.8.4=py36h8f6f2f9_1004
  - mock=4.0.3=py36h5fab9bb_1
  - nb_conda=2.2.1=py36h5fab9bb_4
  - nb_conda_kernels=2.3.1=py36h5fab9bb_0
  - nbconvert=5.6.1=py36h9f0ad1d_1
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - networkx=2.3=py_0
  - nglview=3.0.3=pyh8a188c0_0
  - notebook=6.3.0=py36h5fab9bb_0
  - numexpr=2.7.3=py36h0cdc3f0_0
  - numpy=1.19.5=py36hfc0c790_2
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.1.5=py36h284efc9_0
  - pandoc=2.14.2=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - patsy=0.5.1=py_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=21.2.4=pyhd8ed1ab_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt_toolkit=1.0.15=py_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py36h8f6f2f9_2
  - pytables=3.6.1=py36he0b5dfd_4
  - python=3.6.13=hffdb5ce_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.6=2_cp36m
  - pytz=2021.1=pyhd8ed1ab_0
  - pyzmq=22.2.1=py36h7068817_0
  - readline=8.1=h46c0cb4_0
  - scipy=1.5.3=py36h81d768a_1
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=57.4.0=py36h5fab9bb_0
  - simplegeneric=0.8.1=py_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=he1b5a44_3
  - sqlite=3.36.0=h9cd32fc_0
  - statsmodels=0.12.2=py36he33b4a0_0
  - terminado=0.11.1=py36h5fab9bb_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - tornado=6.1=py36h8f6f2f9_1
  - traitlets=4.3.3=py36h9f0ad1d_1
  - typing_extensions=3.10.0.0=pyha770c72_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - widgetsnbextension=3.5.1=py36h5fab9bb_4
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
